name: wethr
version: "1.4.0"
summary: Command line weather tool.
description: Get current weather.
confinement: strict
base: core18
#adopt-info: test
apps:
  wethr:
    command: wethr
    plugs:
      - network
parts:
  wethr:
    plugin: nodejs
    source-tag: "v1.4.0"
    source: https://github.com/twobucks/wethr.git
