name: apache 
version: '0.1'
summary: apache
description: |
  This is a apache example

grade: stable
#confinement: strict
confinement: devmode 

apps:
  apache:
    command: apr 
  #apache-version:
  #  command: apache --version

parts:
  #my-python-app:
  #  source: https://github.com/liu-xiao-guo/python-helloworld.git
  #  plugin: python
  #  after: [python]
  
  apr:
    source: apr-1.7.0 
    plugin: autotools
    

#  apr-util:
#    source: apr-util-1.6.1
#    plugin: autotools
#
#  apache:
#    #source: https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
#    source: httpd-2.4.41
#    plugin: autotools
#    after: [apr, apr-util]
#    configflags:
#        #- "-DCMAKE_INSTALL_PREFIX=/usr"
#        - "--with-apr=apr"
#        - "--with-apr-util=apr-util"
#
#    #configflags: [--prefix=/usr]
#    #build-packages: [libssl-devl]
#    #build-packages: [libssl-dev, apr, apr-util]
#    prime:
#      - -usr/include
#
