name: nginx
version: "1.16.1"
summary: Nginx 
description: |
  x86 emulator with Tandy/Herc/CGA/EGA/VGA/SVGA graphics, sound and DOS
  DOSBox is a x86 emulator with Tandy/Hercules/CGA/EGA/VGA/SVGA graphics
  sound and DOS. It's been designed to run old DOS games under platforms that
  don't support it.
  .
  The following legacy sound devices are emulated; PC Speaker, Creative,
  CMS/Gameblaster, Tandy 3 voice, Adlib, Sound Blaster Pro/16,
  Disney Soundsource and a Gravis Ultrasound. MPU-401 is forwarded to the host.
confinement: devmode 
#confinement: strict

apps:
  nginx:
    command: sbin/start.sh 
    #command: nginx  -c $SNAP/conf/nginx.conf
    #command: nginx  -c $SNAP/conf/nginx.conf --error-log-path=$SNAP/log/nginx/error.log  --http-log-path=$SNAP/log/nginx/access.log
    #command: nginx  -c $SNAP/nginx-1.16.1/conf/nginx.conf
    plugs: [network-bind]
    #plugs: [network, network-bind, unity7, opengl, home, pulseaudio]

  run:
    command: sbin/nginx -c /var/snap/nginx/current/conf/ginx.conf 
    #command: nginx  -c $SNAP/conf/nginx.conf
    #command: nginx  -c $SNAP/conf/nginx.conf --error-log-path=$SNAP/log/nginx/error.log  --http-log-path=$SNAP/log/nginx/access.log
    #command: nginx  -c $SNAP/nginx-1.16.1/conf/nginx.conf
    plugs: [network-bind]
    #plugs: [network, network-bind, unity7, opengl, home, pulseaudio]

  localrun:
    command: sbin/nginx -c /etc/conf/nginx.conf 
    #command: nginx  -c $SNAP/conf/nginx.conf
    #command: nginx  -c $SNAP/conf/nginx.conf --error-log-path=$SNAP/log/nginx/error.log  --http-log-path=$SNAP/log/nginx/access.log
    #command: nginx  -c $SNAP/nginx-1.16.1/conf/nginx.conf
    plugs: [network-bind]
    #plugs: [network, network-bind, unity7, opengl, home, pulseaudio]

parts:
  source:
    plugin: dump
    source: . 
    organize:
        start.sh: sbin/start.sh 
        stop.sh: sbin/stop.sh 
    source-type: local
  nginx:
    plugin: dump 
    source: nginx-1.16.1/   
    source-type: local

    plugin: autotools
    build-packages:
      - g++
      - make
      - libsdl1.2-dev
      - libpng12-dev
      - libsdl-net1.2-dev
      - libsdl-sound1.2-dev
      - libasound2-dev


