name: pythonserver
version: 2.0
summary: a simple python server
description: This is the webserver API in python demo
confinement: strict
grade: stable
icon: icon.png

apps:
  mywebserver:
    command: bin/server
    #plugs: [ network-client, network-service ]
    plugs: 
    - network-bind
    - network

parts:
  server:
    plugin: python
    source: .

  source:
    plugin: copy
    files:
      ./server.py: bin/server
