name: tomcat
version: 8.0.29
architectures:
 - amd64
summary: A snap for tomcat 
confinement: devmode 
description: This is a demo snap produced by snapcraft.

apps:
 tomcat:
   command: bin/startup.sh
   #command: bin/wrapper
   #daemon: simple
   plugs: [network-bind]


parts:
    tomcat:
        plugin: dump
        source: apache-tomcat-8.0.29
        #source: ../apache-tomcat-8.0.29
        source-type: local

        #build-snaps:
        #- java

        #stage-packages:
        # - jdk
        #- java
        #configflags:
        # - "-JAVA_HOME="

    #local-files:
    #    plugin: make
    #    source: .



