name: mypython # you probably want to 'snapcraft register <name>'
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: python env with modules # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots



apps:
    mypython:
      command: python
      plugs:
        - network
        - home 

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: python 
    python-version: python2
    requirements:
      - requirements.txt
    #python-packages:
    #  - tornado
    #  - torndb
    #  - ansible
    #  - six 
    #  - requests
    #  - redis
    #  - MySQL-python
    #  #- mysqlclient 
    # 
